// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDe39P2mi78_cTQNhFGw6aYawpqjuWd0kM',
    appId: '1:841837640716:web:76501624f23ed54013c229',
    messagingSenderId: '841837640716',
    projectId: 'todoapp-a6b3d',
    authDomain: 'todoapp-a6b3d.firebaseapp.com',
    storageBucket: 'todoapp-a6b3d.appspot.com',
    measurementId: 'G-7SRKBBCVGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgRA_NKtZMhpi6b_UnAv9uKX6V1c8wqc',
    appId: '1:841837640716:android:964b2e58303d0a6013c229',
    messagingSenderId: '841837640716',
    projectId: 'todoapp-a6b3d',
    storageBucket: 'todoapp-a6b3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCShcADasmifpZPfCoJjU3eaQD-L5xc5V0',
    appId: '1:841837640716:ios:d0d96dddb3bb0a7a13c229',
    messagingSenderId: '841837640716',
    projectId: 'todoapp-a6b3d',
    storageBucket: 'todoapp-a6b3d.appspot.com',
    iosBundleId: 'com.example.todoproj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCShcADasmifpZPfCoJjU3eaQD-L5xc5V0',
    appId: '1:841837640716:ios:d0d96dddb3bb0a7a13c229',
    messagingSenderId: '841837640716',
    projectId: 'todoapp-a6b3d',
    storageBucket: 'todoapp-a6b3d.appspot.com',
    iosBundleId: 'com.example.todoproj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDe39P2mi78_cTQNhFGw6aYawpqjuWd0kM',
    appId: '1:841837640716:web:b327fe277fd0934613c229',
    messagingSenderId: '841837640716',
    projectId: 'todoapp-a6b3d',
    authDomain: 'todoapp-a6b3d.firebaseapp.com',
    storageBucket: 'todoapp-a6b3d.appspot.com',
    measurementId: 'G-BS7QT7553B',
  );
}
